export enum SessionStatus {
  INITIAL_REGISTRATION = "INITIAL_REGISTRATION",
  MEETING_PENDING = "MEETING_PENDING",
  CONTRACT_PENDING = "CONTRACT_PENDING",
  SCHEDULED = "SCHEDULED",
  EDITING_PENDING = "EDITING_PENDING",
  DELIVERED = "DELIVERED",
  CANCELED = "CANCELED",
}
